"""link urls to users

Revision ID: 3071469ba9b9
Revises: 70d1ca1b3168
Create Date: 2025-06-12 20:23:31.730106

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3071469ba9b9'
down_revision: Union[str, None] = '70d1ca1b3168'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('urls', sa.Column('user_id', sa.UUID(), nullable=True))
    op.create_index(op.f('ix_urls_user_id'), 'urls', ['user_id'], unique=False)
    op.create_foreign_key(None, 'urls', 'users', ['user_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'urls', type_='foreignkey')
    op.drop_index(op.f('ix_urls_user_id'), table_name='urls')
    op.drop_column('urls', 'user_id')
    # ### end Alembic commands ###
